
# Options related to the Meat Rack. It is used to decay rotten meat to leather and then to bone
[meat-rack]
	#Range: 1 ~ 100000
	"Tick Amount Before Leather, 20 ticks = 1s" = 2400
	#Range: 1 ~ 100000
	"Tick Amount Before Bone, 20 ticks = 1s" = 2400

# Options related to the Honey Pond. It is used to heal the player and can be refilled with honey bottle
[honey-pond]
	#Range: 0 ~ 100000
	"Max Healing Charges" = 10
	#Range: 0 ~ 100000
	"Health Restored Per Use" = 6
	#Range: 0 ~ 100000
	"Healing Charges Restored By Honey Bottle" = 5

# Options related to the Xp Storage. It stores and gives back player experience
[xp-storage]
	#Range: 0 ~ 1000000
	"Maximum Stored Experience" = 2000

# Options related to explosion when breaking Coal Ore blocks with Iron Pickaxe.
[iron_on-coal-explosion]
	"Enable Iron Pickaxe On Coal Block Explosion" = true
	#Range: 0.0 ~ 1.0
	"Chance Of Explosion" = 0.03

[obelisk]
	"Default Obelisk Xp Values In Creative Tab" = [250, 500, 1000, 1500]
	"Can Obelisk Be Destroyed" = false

[mud-trap]
	#Range: 0 ~ 100
	"Default Height Of The Mud Trap Poison Gas" = 3
	#Range: 0 ~ 100
	"Default Diameter Of The Mud Trap Poison Gas" = 1

[spawners]

	[spawners.spider-eggs]
		#Range: 1 ~ 1000
		" Horizontal Detection Range Of Spider Eggs In Blocks" = 10
		#Range: 1 ~ 1000
		" Y Detection Range Of Spider Eggs" = 4

		[spawners.spider-eggs." Mobs spawning when activated"]
			" Formatted like 'mob namespace; weight'" = ["minecraft:spider;20"]

[reset-trades]
	# Whether the reset trade button is enabled or not
	" Reset Trade Enabled" = true
	# Amount of item removed at each reset merchant trade
	#Range: 0 ~ 100000
	" Reset Trade Item Amount Cost" = 2
	# Item removed at each reset merchant trade
	"Reset Trade Item Cost" = "minecraft:emerald"
	# Horizontal position offset of Reset Trade Button in Merchant Trade Screen
	#Range: -10000 ~ 10000
	"Reset Trade Button Offset X" = 0
	# Vertical position offset of Reset Trade Button in Merchant Trade Screen
	#Range: -10000 ~ 10000
	"Reset Trade Button Offset Y" = 0

[integration]

	[integration.legendary-survival-overhaul]
		# Amount of health restored of the most damaged limb at each honey pond consumption
		#Range: 0 ~ 10000
		"Limb Health Restored" = 10

