
#Stamina to let the player run and do stuff.
[Stamina]

	[Stamina.Stamina]
		#How much stamina the player has per half heart. Each 1 stamina is 1 tick of running
		#Range: > 0
		"Per half heart" = 10
		#Range: > 0
		"Bonus per level of vigour enchantment" = 40
		#Range: > 0
		"Bonus per level of vigour effect" = 40
		#Range: 0.0 ~ 1.7976931348623157E308
		"Percentage reduction per armor point" = 0.025
		#If enabled, max stamina will always be bound to max health and no longer with current health
		"Bound to max health" = false

	[Stamina.Consumption]
		#How much stamina the player consumes each tick when sprinting
		#Range: 0.0 ~ 1.7976931348623157E308
		Sprint = 1.0
		#How much stamina the player consumes on each jump
		#Range: > 0
		Jump = 10
		#How much stamina the player consumes each tick when swimming
		#Range: 0.0 ~ 1.7976931348623157E308
		Swim = 0.5
		#Multiplier for stamina consumed when the player is swimming with the conduit power effect.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Conduit swimming modifier" = 0.85
		#How much stamina the player consumes each tick when mining. If stamina is locked, mining speed is halved
		#Range: 0.0 ~ 1.7976931348623157E308
		Mine = 0.0
		#Stamina consumption will be multiplied by this value when the player is out of combat. Out of combat = not attacked or hurt in the last 15 seconds
		#Range: 0.0 ~ 1.7976931348623157E308
		"Out of combat multiplier" = 0.8

	[Stamina.Regen]
		#Range: 0.0 ~ 1.7976931348623157E308
		"Per tick" = 2.0
		#Multiplier for the regen per tick when stamina is locked
		#Range: 0.0 ~ 1.7976931348623157E308
		"Modifier when locked" = 0.6
		#Multiplier for the regen per tick when player's in water
		#Range: 0.0 ~ 1.7976931348623157E308
		"Modifier when in water" = 1.0
		#'Modified when in water' is applied only when the player is not on the ground
		"Modifier when in water when off ground" = true
		#Percentage reduction per armor point
		#Range: 0.0 ~ 1.7976931348623157E308
		"Reduction per armor point" = 0.025

	[Stamina.Lock]
		#When max stamina goes below this percentage, stamina will be locked. With locked stamina, the player can't sprint
		#Range: 0.0 ~ 1.0
		"Below health ratio" = 0.2
		#At which health percentage will stamina be unlocked
		#Range: 0.0 ~ 1.0
		"Unlock at health ratio" = 0.4
		#If this > 0, the player will still be able to sprint when stamina is locked, at the cost of a great amount of hunger. Stamina consumed will be applied to exhaustion at this rate. By default consumed 1 hunger/saturation per second of sprinting
		#Range: 0.0 ~ 1.7976931348623157E308
		"Consume hunger ratio" = 0.1

	[Stamina.Slowdown]

		[Stamina.Slowdown.Sprinting]
			#Below this percentage stamina, sprinting will be less effective.
			#Range: 0.0 ~ 1.0
			Threshold = 0.2
			#Below this stamina amount, sprinting will be less effective.
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			"Threshold flat" = 40.0
			#Slowdown sprinting and swimming by this amount, vanilla sprint is x1.3
			#Range: 0.0 ~ 1.0
			Amount = 0.15

		[Stamina.Slowdown."When locked"]
			#If stamina is locked, player will be slowed down.
			Enabled = true
			#Range: 0.0 ~ 1.0
			Amount = 0.1

	[Stamina.Disable]
		#Disable sprinting altogether
		Sprinting = false
		#Disable swimming altogether
		Swimming = false

